[package]
name = "aoc2023-day4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"
regex = "1.10.2"
thiserror = "1.0.56"
